FROM openjdk:8u111-jre-alpine

#Workspace
WORKDIR /usr/share/mydocker

#ADD .jar under target from host into this image
ADD target/selenium-docker.jar 		selenium-docker.jar
ADD target/selenium-docker-tests.jar 	selenium-docker-tests.jar

#ADD suite files
ADD testng.xml				testng.xml

#BROWSER, HUB_HOST, MODULE

ENTRYPOINT java -cp selenium-docker.jar;selenium-docker-tests.jar;libs/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE

